"""
389. Find the Difference
Easy

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        sletters = {}
        tletters = {}
        for c in list(s):
            sletters.setdefault(c, 0) 
            sletters[c] += 1
        for c in list(t):
            tletters.setdefault(c, 0) 
            tletters[c] += 1
        for k, v in tletters.items():
            if k not in sletters:
                return k
            if sletters[k] != v:
                return k
